project_id = "qivqdltstmlxbcaldjzs"

[functions.rewrite-need]
verify_jwt = false

[functions.send-phone-otp]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
